#!/bin/bash

if [[ $1 -ge $2 && $1 -ge $3 ]]; then
  echo $1 is the maximum number.
elif [[ $2 -ge $1 && $2 -ge $3 ]]; then
  echo $2 is the maximum number.
elif [[ $3 -ge $1 && $3 -ge $2 ]]; then
  echo $3 is the maximum number.
fi
